from .battery import Battery
from .bluetooth import Bluetooth
from .clock import Clock
from .cpu import Cpu
from .disk import Disk
from .headset import Headset
from .network import Network
from .volume import Volume
from .weather import Weather
from .windowtitle import WindowTitle
from .workspaces import Workspaces
